### ISSUE TITLE
TV/Fury3's Big font found!

### ISSUE THREAD

**Issue by StrikerMan780** [jtrfp/terminal-recall#102]
A friend of mine (smoke_fumus) has managed to find the original font for the TV and Fury3 pickup messages and whatnot. Crillee -

http://www.azfonts.net/load_font/crill1.html
http://ufonts.com/download/crillee-italic-bt/121246.html

Edit: This one is with the plain style numbers like in Fury3 (So this one is the one you should use): http://www.azfonts.net/load_font/crille.html

It's considered a commercial font, so I don't know what it'll entail, but make sure to check the license to be safe. Though, considering the games themselves use the font, it should be fine. (Just like if someone manually up-res'd the font.)

**Comment by StrikerMan780** [comment]
Updated the first post with the correct font with the numbers. Crillee Plain. That one seems free too.

See: http://puu.sh/iO4bU/31e079cdf1.png

**Comment by TheTrustedComputer** [comment]
Wow, what a nice find! I though at first the font used in Fury3 and TV was original and made by scratch. I guess not...but anyways the font really fits the game as a whole.

**Comment by cjritola** [comment]
Welp, the font has been on [this repo](https://github.com/wrstone/fonts-startrek) for 8 years without issue, and it's GPL3, so I'm going to give this a shot.

**Comment by cjritola** [comment]
![trcl-crillee](https://user-images.githubusercontent.com/1056698/156476864-df9c2e74-3c6e-4f12-bddb-fe6e3a48be37.png)
