### ISSUE TITLE
Persistent Graphical Artifacts Issues

### ISSUE THREAD

**Issue by Uriz3n** [jtrfp/terminal-recall#104]
I've been experiencing severe graphical artifacts while using this program for several months now. These issues have persisted across numerous builds, and appear similar - albeit more severe - to the closed primitive corruption issue https://github.com/jtrfp/terminal-recall/issues/60

Demonstration;
https://www.youtube.com/watch?v=PG82S76NIms

Log File;
https://www.mediafire.com/?yzixb4l949fqu5u

System;
Windows 7 Ultimate x64
i5-4690K 
GeForce GTX 760 2GB Driver v. 353.06
Kingston HyperX 2x4GB RAM

**Comment by cjritola** [comment]
Thanks for the report. This also resembles #99 . Will try to reproduce the issue locally and raise priority for a fix. A fix may stop two bugs at the same time.

**Comment by cjritola** [comment]
The closest I have on hand at the moment is 352.21 and I was unable to reproduce the issue. Are you using any outside augmentation tool to force mip-mapping or anisotropic filtering? If so, does the issue resolve when the overrides are turned off?

**Comment by Uriz3n** [comment]
Hi cjritola! Many thanks for your response. 

AF is disabled in Nvidia Control Panel, and doesn't appear to impact the issue. This issue has recurred across numerous builds - as well as Nvidia driver versions - for a span of several months.

**Comment by cjritola** [comment]
Does this issue persist?
