### ISSUE TITLE
Solid black textures after several level loads.

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#112]
After several loads, DEF model textures are loading all black. This doesn't seem to be affecting terrain textures as much. Also not consistent; some runs lack the issue.

![black-nonterrain](https://cloud.githubusercontent.com/assets/1056698/9485265/fe415b80-4b84-11e5-9159-592f6b162828.png)
in6)

**Comment by cjritola** [comment]
Spoke too soon, here's terrain with black textures:
![more-black](https://cloud.githubusercontent.com/assets/1056698/9487547/b6eca46c-4ba0-11e5-9a6a-1f52d5b647ec.png)

**Comment by WDLmaster** [comment]
In my tests it's the other way around: after the 4th level load, some terrain textures are black while model textures are all intact.

Unrelated to textures: there's a problem with (some?) tunnels. In ARTIC6.LVL, after entering the boss' tunnel, the player is placed quite a distance off the tunnel start position and colliding all the time with "nothing". The same happens when entering any of the 3 boss chamber tunnels.

**Comment by cjritola** [comment]
Yes there's definitely a tunnel entry problem. Even the portal cameras get confused and you can see a gray gradient of nothingness in the entrance. I've been brainstorming possible causes and will be going forward with fix attempts in about a week. The problem occurs randomly but tends to happen after the first or second mission load, regardless of which missions those may be and worsens with time.

**Comment by cjritola** [comment]
b7a03e572f5e7ede5dafe2d211238c0f411f9e95
716255fe4839766c81a19162ab9a86899d49eb98

**Comment by cjritola** [comment]
Issue persists... -.-

**Comment by cjritola** [comment]
What appears to be happening is the page address for the TOC of new textures is getting out of their allowable maximum of 65535. The first sign of this is the black texture because the last few TOC indices are special values to indicate portals, and if a portal is off then the rendering to that portal will be empty black. Beyond 65535 the float value will rollover such that the exponent increments, resulting in undefined behavior which would include an invalid TOC magic number error if checking was enabled in the deferred shader. (Magenta fragment color)

**Comment by WDLmaster** [comment]
I kinda understand what's causing the issue but why do you get such high texture counts in the first place? Don't you free every allocated texture before you load the next level? Do you simply keep every loaded texture for later re-use? Does it also explain the increasing RAM usage after every level load? But 65535 textures is more than the sum of textures of all 3 games combined (roughly 3700). So even if you load ALL 3 games completely into RAM, it would never reach 65535.

**Comment by cjritola** [comment]
Part of the reason this bug hangs on so long is the complexity of the system below it.

There is a section of GPU memory I allocated which I refer to as a 'root buffer' which is common general-purpose storage for vertices, texture table-of-contents (TOC), subtexture tables, matrices, but not actual texel data. Actual texel data is stored in codebooks.

The root memory is split into pages 1536 bytes long which are allocated and (supposed to be) released with demand for whatever resource they are being used for. When pages are needed by the game, it always takes the free pages of the lowest position to minimize fragmentation. The texture TOC address simply refers to the page number, but doesn't necessarily imply that all pages previous to it contain anything involving textures.

That said, page 65536 is at the 96MB mark, which is more root buffer usage than I had calculated should happen. On top of this, it occurs later in loading. These two factors point at some resources not being released properly, not necessarily texture-related.

Another consideration is internal fragmentation. ( https://en.wikipedia.org/wiki/Fragmentation_(computing)#Internal_fragmentation ) One of the MemoryWindows may have a lot of unused pages which aren't being released back to the parent buffer. MatrixWindow comes to mind...

**Comment by cjritola** [comment]
Making progress, Confirming that page are not being released properly. The MemoryManager is not being sufficiently informed of released pages, resulting in abandoned pages. Eventually all free pages end up abandoned, making the MemoryManager unaware of them and thinking it is out of memory and allocating further and further up the address space. This is why we are passing the 96MB mark: It's not actually using that much memory, rather it is using a small chunk of it, releasing it, forgetting it is available, and allocating future resources further up the address space such that the root buffer grows and grows with forgotten pages.

**Comment by cjritola** [comment]
Making progress; there seem to be a few things wrong which are in the process of being ironed out.

**Comment by WDLmaster** [comment]
Is the latest memory-consumption-reduction-fix already implemented? Because yesterday (or so) I installed the latest TRCL and couldn't see any change in memory consumption on the test PCs (haven't tested it on the regular PC because it has tons of RAM).

**Comment by cjritola** [comment]
Not the type you're describing, no. I still haven't figured out what exactly it is that is taking all of that space. The parts I know I can control are using ~300MB, the rest is still unaccounted for but I still see the 1GB usage too.

The bug featured here has to do with the black textures because of a VRAM mismanagement error on my part.

**Comment by cjritola** [comment]
Looks like this bug is finally squashed.
