### ISSUE TITLE
Tunnel entrance failure in EGYPT3

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#137]
Somewhere down the line some (not all) tunnel entrances have failed to trigger on collision, particularly in EGYPT3.LVL and some DESERT chamber exits.

**Comment by WDLmaster** [comment]
If you mean the tunnel at [19, 196] then it might be caused by two overlapping tunnels. Tunnel 3's entrance and tunnel 4's (invisible) exit share the same terrain cell. The MINE levels also have setups like this.
