### ISSUE TITLE
Create a program icon

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#142]
Need a program icon for Terminal Recall.
* Resolution: 256 x 256
* Format: PNG
* Must consent to distribution by the terms of version 3 of the GNU General Public License.
* I will add your name to the credits.
* Image should be generically representative of TV/Fury3/Hellbender.
* Text discouraged.
* If interested, make a comment that you're going to work on it (or assign yourself) so multiple people don't take the same task.

**Comment by WDLmaster** [comment]
![icon1](http://www.wdlmaster.de/TRCL/icon1.png)

**Comment by cjritola** [comment]
If those are the models and textures from the original games I can't GPL it. Sorry. ):

**Comment by cjritola** [comment]
I am putting a temporary hold on this on the prospect of an illustrator (outside of GitHub) making this icon.
