### ISSUE TITLE
Unimplemented logic 42 in EGYPT3.

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#47]
Old but previously undocumented bug:
FURY3.POD\DATA\EGYPT3.DEF line 2.

Boss in FURY3\EGYPT3 uses unimplemented logic 42, resulting in exception.

**Comment by TheTrustedComputer** [comment]
According to the F!Zone level editor, this logic is called Anubis, the final boss of Sebek. The logic describes, the thrust speed will let the game know what to shoot on at an frame of an animated model.

**Comment by cjritola** [comment]
Looking at videos on youtube it looks like a stream of 5 projectiles fires at that specified frame.
