### ISSUE TITLE
Failure to run on Intel HD 4000 GPU

### ISSUE THREAD

**Issue by ghost** [jtrfp/terminal-recall#50]
Hello,

I tried to use Terminal Recall on ArchLinux x86_64, using a Intel HD 4000 GPU.
The md5 hash of my POD files are the following

```
095d4bf9561e15fb17b6dcfd9ce6ec60  FURY3.POD
7c560e52de3315afffc08bdbf2300d96  STARTUP.POD
```

At launch, using the example command, it displays an unusable window, sometimes garbled, sometimes not with the following output, and just hangs there.

```
Overriding the default JVM settings. If you wish to manually set the JVM settings, include the `-Dorg.jtrfp.trcl.bypassConfigure=true` flag in the java command.
Restarting JVM with: 
        java -Xmx1024M -Dorg.jtrfp.trcl.bypassConfigure=true -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:+UseFastAccessorMethods -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=5 -XX:+AggressiveOpts -XX:+UseBiasedLocking -XX:+AlwaysPreTouch -XX:ParallelGCThreads=4 -Xms512m  -Dorg.jtrfp.trcl.flow.Game.skipToLevel=EGYPT.LVL -jar RunMe.jar STARTUP.POD FURY3.POD
                        ***TERMINAL RECALL***
        An unofficial enhancement engine for Terminal Velocity and Fury3.
        Copyright (c) 2012-2014 Chuck Ritola and contributors. See enclosed CREDITS file for details.
        Part of the Java Terminal Reality File Parsers Project.

                This program is free software; you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation; either version 3 of the License, or
        (at your option) any later version.
                This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.
        You should have received a copy of the GNU General Public License
        along with this program; if not, write to the Free Software Foundation,
        Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

                THIS PROGRAM IS NOT SUPPORTED BY OR AFFILIATED WITH MICROSOFT OR TERMINAL REALITY INC.
        Bring any issues to the Terminal Recall GitHub page.
        www.jtrfp.org

Initializing graphics engine...
...Done
GLEventListener.init()
0:27(1): error: if a fragment input is (or contains) an integer, then it must be qualified with 'flat'
X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 1/1, reusable (open, marked uncloseable): 0, pending (open in creation order): 1)
X11Util: Open X11 Display Connections: 1
X11Util: Open[0]: NamedX11Display[:0.0, 0x7f8f44010e70, refCount 1, unCloseable false]
```

How can I help you debug this?

**Comment by cjritola** [comment]
A number of changes were made to the portions of TRCL responsible for the errors on your hardware.

The possibility of the newest build working on your HD 4000 is not optimistic as I was getting a blank screen with the onboard Intel graphics on the testbench but there is still a possibility that the issue was fixed on your hardware, which I don't have.

If you are in an adventurous mood, feel free to report back on your findings.

**Comment by grrk-bzzt** [comment]
Launching the software with the command `java -jar RunMe.jar` just generate a blank window and output the following : https://gist.github.com/grrk-bzzt/fc523d2399f8a0ca88ed

**Comment by cjritola** [comment]
A significant bugfix has recently been committed which makes Terminal Recall playable on Intel 4600. I don't have an HD 4000 to test on, but there is a chance that it can run.

It would be great if someone verify at their convenience whether or not this works on an Intel HD4000

**Comment by grrk-bzzt** [comment]
Hello,
Unfortunately, my HD 4000 broke two months ago. I've switched to a GeForce GTX 970.
Still, the game doesn't work.

**Comment by cjritola** [comment]
Did you try with the newest build today?

**Comment by grrk-bzzt** [comment]
Yes I did. I've cloned the latest revision right now.

**Comment by cjritola** [comment]
#125

**Comment by cjritola** [comment]
Many redesigns in the rendering pipeline since this bug was filed. Does it persist?

**Comment by marespiaut** [comment]
Sorry, I don't have an HD 4000 anymore. I can't test it for you.

**Comment by marespiaut** [comment]
Sorry, I don't have an HD 4000 anymore. I can't test it for you.

**Comment by grrk-bzzt** [comment]
Sorry, I don't have an HD 4000 anymore. I can't test it for you.
