### ISSUE TITLE
[VC++ Runtime Err] Pure virtual function call

### ISSUE THREAD

**Issue by stevenstrike** [jtrfp/terminal-recall#59]
Hi,
When starting runMe.jar (with latest revision and from my 9th december pull i think), a window from the MS Visual C++ Runtime Library tell me that there is a pure virtual function call from java.exe

No problem during compilation whatsoever.

R6025 - Pure virtual function call
"The most common error I've seen that causes this is calling a virtual function from a base class constructor or destructor."

![councilor_is_naughty](https://cloud.githubusercontent.com/assets/9658688/5401371/1af73f4e-817b-11e4-8ecc-2946f79dc30e.png)

Rookie java dev' here, but i find amusing that the JDK compiler isn't reporting some warning/error about this during the maven clean install script.

Thanks for reading.

**Comment by cjritola** [comment]
Are you still having this issue? I installed 14.501.1003 from ubuntu's repos with success but the manual package creation and install from AMD would get me that error.

**Comment by stevenstrike** [comment]
Yes unfortunately, i will do a fresh uninstall/cleanup and reinstall the AMD Omega driver, and report back !

**Comment by cjritola** [comment]
Glad it's running! Good work finding the driver bug; will make a note of it. The the idea of a driver breaking a program right after a $$$ release is scary, especially this type as it breaks java's ability to print a stacktrace to the problem.

Your screenshot looks as expected, known bugs and all. The quantized graininess of the color seems to be a quirk with AMD and RGBA4 format. It looks reminiscent of compression chroma artifacts but I am not certain exactly what is happening to cause it.

**Comment by stevenstrike** [comment]
Just got the new 14.502.1002 drivers (these are not official though, since i found them on an archive provided by Dell : http://www.guru3d.com/files-details/amd-catalyst-15-x-download.html

No more VC++ Runtime error, BUT (sigh) now i can only see the black skybox filled with stars (briefing mode) : 
![furywhoops1](https://cloud.githubusercontent.com/assets/9658688/5857699/123d5f34-a24e-11e4-9ff0-6f58fcd2796c.png)
 and when i press space to skip this, i end up having this : 
![furywhoops2](https://cloud.githubusercontent.com/assets/9658688/5857707/174e3a16-a24e-11e4-834c-c6bca4f2e5a4.png)

**Comment by cjritola** [comment]
An AMD thread possibly related to this:
http://devgurus.amd.com/thread/169678

**Comment by stevenstrike** [comment]
[**@cjritola**](https://github.com/cjritola) commented on [24 avr. 2015 03:02 UTC+2](https://github.com/jtrfp/terminal-recall/issues/59#issuecomment-95765577 "2015-04-24T01:02:59Z - Replied by Github Comment Enhancer"):
> An AMD thread possibly related to this:  
> 
> [http://devgurus.amd.com/thread/169678](http://devgurus.amd.com/thread/169678)
> 
> In a few weeks I will be looking deeper into this.

Thank you ! Also the problem is still present on the last beta driver (aka GTA V fix)

**Comment by cjritola** [comment]
If you've tried fglrx 15.20, will it start up for you without the driver crashing?

On my end it will run without a crash but will not render properly. This is a step forward as it gives me an opportunity to debug.

**Comment by stevenstrike** [comment]
No more issues with last revision of Terminal Recall and Catalyst 15.4Beta (also no more issue with shaders), will try on Arch with open source drivers (xf86-video-ati) and close this bug report if everything is working.

**Comment by cjritola** [comment]
Great!

**Comment by stevenstrike** [comment]
Good Job ! @cjritola 

Arch Linux Amd open-source drivers (xf86-video-ati) works fine, performance is meh but i'll put this on the back of OSS drivers; didnt test with the 'catalyst' driver (official, closed source, one) because i need to revert X to a fixed version and catalyst loves to break stuff, so i prefer to take my distances with this :p 

Did not try the latest Catalyst 15.7 WHQL for windows, i'll check tomorrow and post if something is wrong.

Again well done !

**Comment by cjritola** [comment]
Side note: Performance can be improved by adding -Dorg.jtrfp.trcl.debugGL=false to the java command just before the -jar flag. This isn't recommended in testing stage as this can omit important information if there is a problem.
