### ISSUE TITLE
Animated tunnel segments (i.e. rotating) occasionally have wide gaps.

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#79]
Animated tunnel segments (i.e. rotating) occasionally have wide gaps between them whereas non-animated do not.

**Comment by WDLmaster** [comment]
Can you give an example where that happens? I tested a few tunnels and found nothing wrong in them. The only gaps I noticed are between segments when their angles do not match. This is normal and happens in the original games as well.

**Comment by cjritola** [comment]
ATMOS3.LVL, enter tunnel coord (104,96) proceed to rotating section where DIST=434.

**Comment by WDLmaster** [comment]
Hmm, looks just like the original. TRCL looks even better because the original engine does NOT update the rotation until the segment becomes visible. Those small gaps are normal.

![](http://www.wdlmaster.de/TRCL/atun1.jpg)
![](http://www.wdlmaster.de/TRCL/atun2.jpg)

**Comment by cjritola** [comment]
Yep. ^.^
