### ISSUE TITLE
Implement game save/load

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#87]
Need gamesave/load. Looking at XMLBeans for straightforwardness and abandoning original format other than perhaps file conversions.

This is a big one which will take a while and may manifest bugs.

**Comment by WDLmaster** [comment]
ReWiki is blocked at the moment so I've put my updates here in the meantime, just for you :-D

www.wdlmaster.de/TRCL/dat.html

**Comment by cjritola** [comment]
Thanks :D

**Comment by cjritola** [comment]
OCD question: The offsets you supply are in decimal and not hex, correct?

**Comment by WDLmaster** [comment]
yes, I seldom use HEX (only if my life depends on it, hehe)...

**Comment by WDLmaster** [comment]
I updated the savestate page a bit and found something interesting. Let me quote myself:

"it seems the developers wanted to include some sort of missile tracking or targeting display for seeking missiles but dropped that feature. View mode 3 crashes with "no target view" error and mode 4 with "no missile view" error in both games. Mode(s) 5 and onwards switch to an external, fixed camera that rests on the ground at the map origin. You can bring the player close to the camera and watch it from 3rd person. I think this has something to do with multiplayer in TV (spectator camera for instance). "

Also:
* there's a maximum of 10 tunnels per map
* powerups can have individual "colletion radii". I always though they have a fixed, hardcoded radius!
* the range of numbers in filenames for sprite animations is automatically adapted according to the lifespan and progress parameters of animations. If you increase the lifespan, the game looks for more frames automatically. Not hardcoded, as I always thought.

**Comment by cjritola** [comment]
View 5 reminds me very much of the tower view mode in Microsoft Fight Simulator. It wouldn't surprise me if there is an internal variable to specify the origin position and another variable to specify how far down the line between these two positions to place the camera. This would then be used for the 3rd person view beginning and end of each level, death sequences and perhaps even the satellite view.

I'm guessing mode 3 is used in enemy introduction for briefing mode where 'target view' is an internally settable value for the enemy index.
