### ISSUE TITLE
Satellite View corrupted and freezes game

### ISSUE THREAD

**Issue by StrikerMan780** [jtrfp/terminal-recall#92]
When pressing tab to go into the satellite view, it looks slightly corrupted, and the game permanently freezes. Here is a screenshot:

![Screenshot](http://puu.sh/gnuar/0139ac5085.png)

**Comment by cjritola** [comment]
Confirmed. Very unexpected.

**Comment by StrikerMan780** [comment]
Seems to work fine now.
