### ISSUE TITLE
Corrupt video output

### ISSUE THREAD

**Issue by StrikerMan780** [jtrfp/terminal-recall#96]
Right now, the video output is very corrupt. No display of anything except for the skybox.

![Messed Up](http://puu.sh/i9cMY/628c53b2da.png)

**Comment by cjritola** [comment]
Thanks for the feedback; this should iron out in a few days.

**Comment by WDLmaster** [comment]
Strange. I can confirm that but less severe. There were just random chunks (8 x 8 ?) of terrain missing but after a 2nd launch of the game, everything was completely normal. "Normal" in TRCL terms, which excludes stuttering, sorting errors and green pixels.

**Comment by cjritola** [comment]
The variance you're experiencing is caused by a race condition.

**Comment by StrikerMan780** [comment]
Fixed now, but the game is now very stuttery. Ie. smooth 5 frames, freezes for about half a second, repeat.

**Comment by cjritola** [comment]
It's running out of memory so the GC is going crazy. Major fix should be coming in tomorrow.
